all: windows

windows:
	$(CSC) /unsafe /target:library /r:../glib/glib-sharp.dll /r:../pango/pango-sharp.dll /out:atk-sharp.dll /recurse:*.cs

docs:
	$(CSC) /unsafe /target:library /r:../glib/glib-sharp.dll /r:../pango/pango-sharp.dll /doc:atk-sharp-docs.xml /out:atk-sharp.dll /recurse:*.cs

