<Combine name="profiler" fileversion="2.0">
  <Configurations />
  <DeployTargets />
  <StartMode startupentry="profiler" single="True">
    <Execute type="None" entry="profiler" />
  </StartMode>
  <Entries>
    <Entry filename="./Makefile.am.mdp" />
  </Entries>
</Combine>