variables:
  versionbase: 3.24.24
  increment: $[counter(variables['versionbase'], 1)]
  version: $(versionbase).$(increment)

trigger:
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: 6.0.101
      includePreviewVersions: false

  - script: echo "##vso[build.updatebuildnumber]$(version)"
    displayName: 'Set Build Number'

  - script: ./build.sh --BuildTarget=FullBuild --BuildVersion=$(version)
    displayName: 'CAKE Script'

  - task: PublishBuildArtifacts@1
    displayName: Publish Binaries Artifact
    inputs:
      pathtoPublish: BuildOutput/Release
      artifactName: Binaries
      publishLocation: container

  - task: PublishBuildArtifacts@1
    displayName: Publish NuGet Artifact
    inputs:
      pathtoPublish: BuildOutput/NugetPackages
      artifactName: NuGet
      publishLocation: container

  - task: PublishBuildArtifacts@1
    displayName: Publish Samples Artifact
    inputs:
      pathtoPublish: BuildOutput/Samples
      artifactName: Samples
      publishLocation: container
