#!/bin/sh
# Run this to set configure.in up for an API version.

echo "**********************************************************************" 	 
echo "This bootstrap is totally untested and unsupported." 	 
echo "Use at your own risk.  Don't expect any sort of timely bugfixes." 	 
echo "Don't even expect it to compile."
echo "You have acknowledged your insanity by executing this script." 	 
echo "Seek psychiatric help..." 	 
echo "**********************************************************************"

GTK_SHARP_VERSION=2.7.0.99
ASSEMBLY_VERSION=2.8.0.0
POLICY_VERSIONS="2.4 2.6"
GTK_REQUIRED_VERSION=2.7.0
GNOME_REQUIRED_VERSION=2.10.0
VERSIONCSDEFINES="-define:GTK_SHARP_2_6 -define:GTK_SHARP_2_8"
VERSIONCFLAGS="-DGTK_SHARP_2_6 -DGTK_SHARP_2_8"
GTK_API_TAG=2.8
GNOME_API_TAG=2.10

. ./bootstrap-generic "$@"
