#!/bin/sh
# Run this to set configure.in up for an API version.

GTK_SHARP_VERSION=2.13.90
ASSEMBLY_VERSION=2.14.0.0
POLICY_VERSIONS="2.4 2.6 2.8 2.10 2.12"
GTK_REQUIRED_VERSION=2.14.3
GLIB_REQUIRED_VERSION=2.18.1
MONO_REQUIRED_VERSION=2.2
VERSIONCSDEFINES="-define:GTK_SHARP_2_6 -define:GTK_SHARP_2_8 -define:GTK_SHARP_2_10 -define:GTK_SHARP_2_12 -define:GTK_SHARP_2_14"
VERSIONCFLAGS="-DGTK_SHARP_2_6 -DGTK_SHARP_2_8 -DGTK_SHARP_2_10 -DGTK_SHARP_2_12 -DGTK_SHARP_2_14"
GTK_API_TAG=2.14

. ./bootstrap-generic "$@"

echo ""
echo "                       uuuuuuu"
echo "                  uu\$\$\$\$\$\$\$\$\$\$\$uu"
echo "               uu\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$uu"
echo "              u\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$u"
echo "             u\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$u"
echo "            u\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$u"
echo "            u\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$u"
echo "            u\$\$\$\$\$\$\"   \"\$\$\$\"   \"\$\$\$\$\$\$u"
echo "            \"\$\$\$\$\"      u\$u       \$\$\$\$\""
echo "             \$\$\$u       u\$u       u\$\$\$"
echo "             \$\$\$u      u\$\$\$u      u\$\$\$"
echo "              \"\$\$\$\$uu\$\$\$   \$\$\$uu\$\$\$\$\""
echo "               \"\$\$\$\$\$\$\$\"   \"\$\$\$\$\$\$\$\""
echo "                 u\$\$\$\$\$\$\$u\$\$\$\$\$\$\$u"
echo "                  u\$\"\$\"\$\"\$\"\$\"\$\"\$u"
echo "        uuu        \$\$u\$ \$ \$ \$ \$u\$\$       uuu"
echo "       u\$\$\$\$        \$\$\$\$\$u\$u\$u\$\$\$       u\$\$\$\$"
echo "        \$\$\$\$\$uu      \"\$\$\$\$\$\$\$\$\$\"     uu\$\$\$\$\$\$ "
echo "      u\$\$\$\$\$\$\$\$\$\$\$uu    \"\"\"\"\"    uuuu\$\$\$\$\$\$\$\$\$\$"
echo "      \$\$\$\$\"\"\"\$\$\$\$\$\$\$\$\$\$uuu   uu\$\$\$\$\$\$\$\$\$\"\"\"\$\$\$\""
echo "       \"\"\"      \"\"\$\$\$\$\$\$\$\$\$\$\$uu \"\"\$\"\"\""
echo "                 uuuu \"\"\$\$\$\$\$\$\$\$\$\$uuu\""
echo "        u\$\$\$uuu\$\$\$\$\$\$\$\$\$uu \"\"\$\$\$\$\$\$\$\$\$\$\$uuu\$\$\$"
echo "        \$\$\$\$\$\$\$\$\$\$\"\"\"\"           \"\"\$\$\$\$\$\$\$\$\$\$\$\""
echo "         \"\$\$\$\$\$\"                      \"\"\$\$\$\$\"\""
echo "           \$\$\$\"                         \$\$\$\$\""
echo ""
echo "*** WARNING *** ***WARNING ***"
echo "This bootstrap is UNSUPPORTED and may be UNSTABLE"
echo "with NO SCHEDULED RELEASE DATE!"
echo "Unless you're completly insane, you should use the Gtk# 2.12 branch"
echo "(do not blame Novell if it busts your machine)"
