DIRS=generator glib pango atk gdk gtk gnome sample
ROOT=/cygdrive/$(subst \,/,$(subst :\,/,$(SYSTEMROOT)))
CSC=$(ROOT)/microsoft.net/framework/v1.0.3705/csc.exe

all: windows

windows:
	for i in $(DIRS); do				\
		(cd $$i; CSC=$(CSC) make -f makefile.win32) || exit 1;\
	done;

docs:
	for i in $(DIRS); do				\
		(cd $$i; CSC=$(CSC) make -f makefile.win32 docs) || exit 1;\
	done;

