DIRS=generator parser glib pango atk gdk gtk glade
ROOT=/cygdrive/$(subst \,/,$(subst :\,/,$(SYSTEMROOT)))
CSC=$(ROOT)/microsoft.net/framework/v1.0.3705/csc.exe /d:WIN32

all: windows

windows:
	for i in $(DIRS); do				\
		(cd $$i; CSC="$(CSC)" make -f makefile.win32) || exit 1;\
	done;

clean:
	for i in $(DIRS); do \
		(cd $$i; make -f makefile.win32 clean) || exit 1;\
	done;

release: clean windows
	mkdir lib
	find $(DIRS) -iname "*.dll" -exec cp \{\} lib \;

