all: windows

windows:
	../mapdllnames.pl generated/*.cs
	$(CSC) /unsafe /target:library /r:../glib/glib-sharp.dll /out:pango-sharp.dll /recurse:*.cs

docs:
	$(CSC) /unsafe /target:library /r:../glib/glib-sharp.dll /doc:pango-sharp-docs.xml /out:pango-sharp.dll /recurse:*.cs

