<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <GtkSharpWorkloadVersion>@VERSION@</GtkSharpWorkloadVersion>
    <GtkSharpVersion Condition=" '$(GtkSharpVersion)' == '' ">$(GtkSharpWorkloadVersion)</GtkSharpVersion>
  </PropertyGroup>

  <PropertyGroup>
    <_DefaultGtkTargetPlatformVersion>@GTKSHARPVERSION@</_DefaultGtkTargetPlatformVersion>
  </PropertyGroup>

  <!-- This is the installed workload in use, not the final version in the app -->
  <ItemGroup>
    <ProjectCapability Include="GtkSharp.Workload.Version.@VERSION@" />
  </ItemGroup>

</Project>