<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <UsingGtkSharpSdk>true</UsingGtkSharpSdk>
  </PropertyGroup>

  <Import Project="GtkSharp.Sdk.Before.targets" />

  <!-- Imported last -->
  <PropertyGroup>
    <AfterMicrosoftNETSdkTargets>$(AfterMicrosoftNETSdkTargets);$(MSBuildThisFileDirectory)GtkSharp.Sdk.After.targets</AfterMicrosoftNETSdkTargets>
  </PropertyGroup>

</Project>