<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>GskSharp is a C# wrapper for the Gsk rendering library.</Description>
    <PackageTags>gsk;gsksharp;gsk-sharp;wrapper</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GLibSharp\GLibSharp.csproj">
      <Name>GLibSharp</Name>
    </ProjectReference>
    <ProjectReference Include="..\GioSharp\GioSharp.csproj">
      <Name>GioSharp</Name>
    </ProjectReference>
    <ProjectReference Include="..\CairoSharp\CairoSharp.csproj">
      <Name>CairoSharp</Name>
    </ProjectReference>
    <ProjectReference Include="..\PangoSharp\PangoSharp.csproj">
      <Name>PangoSharp</Name>
    </ProjectReference>
    <ProjectReference Include="..\GrapheneSharp\GrapheneSharp.csproj">
      <Name>GrapheneSharp</Name>
    </ProjectReference>
    <ProjectReference Include="..\GdkSharp\GdkSharp.csproj">
      <Name>GdkSharp</Name>
    </ProjectReference>
  </ItemGroup>

</Project>
