<Project Sdk="Microsoft.Build.NoTargets">

  <PropertyGroup>
    <Description>GtkSharp SDK. Enabled via the net8.0-gtk TFM.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="**\*.in.*" />
    <None Update="@(None)" PackagePath="" CopyToOutputDirectory="PreserveNewest" Pack="true" />
  </ItemGroup>

  <ItemGroup>
    <ReplacementValue Include="@VERSION@" Value="$(Version)" />
    <ReplacementValue Include="@GTKSHARPVERSION@" Value="$(_GtkSharpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ReplacementFile
      Include="Sdk\BundledVersions.in.targets"
      Destination="$(IntermediateOutputPath)BundledVersions.targets"
      Pack="true"
      PackagePath="Sdk\BundledVersions.targets" />
  </ItemGroup>

</Project>