<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Gtk templates for Visual Basic</Title>
    <PackageId>GtkSharp.Template.VBNet</PackageId>
    <PackageId Condition="'$(WorkloadBuild)' == 'true'">GtkSharp.Workload.Template.VBNet</PackageId>
    <Description>A set of Visual Basic templates for your .Net Gtk Application.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ReplacementFile
      Include="content\GtkSharp.Application.VBNet\.template.config\template.in.json"
      Destination="$(IntermediateOutputPath)cs-template.json"
      Pack="true"
      PackagePath="content\content\GtkSharp.Application.VBNet\.template.config\template.json" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="content/**/*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../../Libs/GtkSharp/Icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>