<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>JavaScriptCoreSharp is a C# wrapper for the JavaScriptCore library.</Description>
    <PackageTags>javascriptcore;jsc;javascriptcoresharp;wrapper</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GLibSharp\GLibSharp.csproj">
      <Name>GLibSharp</Name>
    </ProjectReference>
    <ProjectReference Include="..\GioSharp\GioSharp.csproj">
      <Name>GioSharp</Name>
    </ProjectReference>
  </ItemGroup>

</Project>
