<Project Sdk="Microsoft.Build.NoTargets">

  <PropertyGroup>
    <PackageId>$(PackageId).Manifest-$(_GtkSharpManifestVersionBand)</PackageId>
    <Description>GtkSharp workload manifest</Description>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Workaround: Visual Studio complains if the version contains 4 parts (major.minor.patch.rev, the one that GtkSharp is currently using) -->
    <_GtkSharpVersionMajorMinorPatch>$([System.Text.RegularExpressions.Regex]::Match($(Version), '(\d+)\.(\d+).(\d+)'))</_GtkSharpVersionMajorMinorPatch>
    <_GtkSharpManifestVersion>$(Version.Replace('$(_GtkSharpVersionMajorMinorPatch).', '$(_GtkSharpVersionMajorMinorPatch)-rev.'))</_GtkSharpManifestVersion>
  </PropertyGroup>

  <ItemGroup>
    <ReplacementValue Include="@VERSION@" Value="$(Version)" />
    <ReplacementValue Include="@GTKSHARPMANIFESTVERSION@" Value="$(_GtkSharpManifestVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ReplacementFile
      Include="WorkloadManifest.in.json"
      Destination="$(IntermediateOutputPath)WorkloadManifest.json"
      Pack="true"
      PackagePath="data\WorkloadManifest.json" />
    <ReplacementFile
      Include="WorkloadManifest.in.targets"
      Destination="$(IntermediateOutputPath)WorkloadManifest.targets"
      Pack="true"
      PackagePath="data\WorkloadManifest.targets" />
  </ItemGroup>

</Project>