<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(FrameworkParameter)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="MainWindow.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="**\*.ui" />
    <EmbeddedResource Include="**\*.ui">
      <LogicalName>%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Net4x.GtkSharp" Version="4.22.4.*" />
  </ItemGroup>

</Project>
