<Project>

	<PropertyGroup>
		<PackageType>Template</PackageType>
		<PackageId>$([System.String]::Copy('$(MSBuildProjectName)').Replace('Sharp', 'Sharp4'))</PackageId>
		<TargetFramework>netstandard2.0</TargetFramework>
		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateDependencyFile>false</GenerateDependencyFile>
		<IncludeSymbols>false</IncludeSymbols>
		<NoWarn>NU5128</NoWarn>
	</PropertyGroup>

</Project>