<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>GrapheneSharp is a C# wrapper for the Graphene library.</Description>
    <PackageTags>graphene;graphenesharp;graphene-sharp;wrapper</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GLibSharp\GLibSharp.csproj">
      <Name>GLibSharp</Name>
    </ProjectReference>
  </ItemGroup>

</Project>
