<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(FrameworkParameter)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="**\*.ui" />
    <EmbeddedResource Include="**\*.ui">
      <LogicalName>%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="4.22.4.*" />
  </ItemGroup>

</Project>
